// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "i18n.h"
#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include "wizard.h"
#include "folder_open.xpm"
#include "warning.xpm"
#include "question.xpm"
#include <iostream>
#include <string>
using namespace std;


char* G2U(const char* gb2312)
{
int len = MultiByteToWideChar(CP_ACP, 0, gb2312, -1, NULL, 0);
wchar_t* wstr = new wchar_t[len+1];
memset(wstr, 0, len+1);
MultiByteToWideChar(CP_ACP, 0, gb2312, -1, wstr, len);
len = WideCharToMultiByte(CP_UTF8, 0, wstr, -1, NULL, 0, NULL, NULL);
char* str = new char[len+1];
memset(str, 0, len+1);
WideCharToMultiByte(CP_UTF8, 0, wstr, -1, str, len, NULL, NULL);
if(wstr) delete[] wstr;
return str;
}
void Wizard::cb_fg_exe__i(Fl_Input*, void*) {
  fg_exe_update_cb();
}
void Wizard::cb_fg_exe_(Fl_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_fg_exe__i(o,v);
}

void Wizard::cb__i(Fl_Button*, void*) {
  fg_exe_select_cb();
}
void Wizard::cb_(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb__i(o,v);
}

void Wizard::cb_fg_root__i(Fl_Input*, void*) {
  fg_root_update_cb();
}
void Wizard::cb_fg_root_(Fl_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_fg_root__i(o,v);
}

void Wizard::cb_1_i(Fl_Button*, void*) {
  fg_root_select_cb();
}
void Wizard::cb_1(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_1_i(o,v);
}

void Wizard::cb_aircraft_dir_list__i(Fl_Browser*, void*) {
  aircraft_dir_select_cb();
}
void Wizard::cb_aircraft_dir_list_(Fl_Browser* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_aircraft_dir_list__i(o,v);
}

void Wizard::cb_Add_i(Fl_Button*, void*) {
  aircraft_dir_add_cb();
}
void Wizard::cb_Add(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_Add_i(o,v);
}

void Wizard::cb_aircraft_dir_delete__i(Fl_Button*, void*) {
  aircraft_dir_delete_cb();
}
void Wizard::cb_aircraft_dir_delete_(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_aircraft_dir_delete__i(o,v);
}

void Wizard::cb_scenery_dir_list__i(Fl_Browser*, void*) {
  scenery_dir_select_cb();
}           
void Wizard::cb_scenery_dir_list_(Fl_Browser* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_scenery_dir_list__i(o,v);
}

void Wizard::cb_Add1_i(Fl_Button*, void*) {
  scenery_dir_add_cb();
}
void Wizard::cb_Add1(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_Add1_i(o,v);
}

void Wizard::cb_scenery_dir_delete__i(Fl_Button*, void*) {
  scenery_dir_delete_cb();
}
void Wizard::cb_scenery_dir_delete_(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_scenery_dir_delete__i(o,v);
}

void Wizard::cb_scenery_dir_up__i(Fl_Button*, void*) {
  scenery_dir_up_cb();
}
void Wizard::cb_scenery_dir_up_(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_scenery_dir_up__i(o,v);
}

void Wizard::cb_scenery_dir_down__i(Fl_Button*, void*) {
  scenery_dir_down_cb();
}
void Wizard::cb_scenery_dir_down_(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_scenery_dir_down__i(o,v);
}

void Wizard::cb_cache_delete__i(Fl_Button*, void*) {
  delete_cache_file_cb();
}
void Wizard::cb_cache_delete_(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_cache_delete__i(o,v);
}

void Wizard::cb_show_3d_preview_i(Fl_Check_Button*, void*) {
  show_3d_preview_cb();
}
void Wizard::cb_show_3d_preview(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_show_3d_preview_i(o,v);
}

void Wizard::cb_aircraft_mru_i(Fl_Browser*, void*) {
  aircraft_from_mru();
}
void Wizard::cb_aircraft_mru(Fl_Browser* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_aircraft_mru_i(o,v);
}

void Wizard::cb_aircraft_i(Fl_Browser*, void*) {
  preview_aircraft();
}
void Wizard::cb_aircraft(Fl_Browser* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_aircraft_i(o,v);
}

void Wizard::cb_start_viewer_i(Fl_Button*, void*) {
  start_viewer_cb();
}
void Wizard::cb_start_viewer(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_start_viewer_i(o,v);
}

void Wizard::cb_show_all_apt_i(Fl_Round_Button*, void*) {
  show_installed(false);
}
void Wizard::cb_show_all_apt(Fl_Round_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_show_all_apt_i(o,v);
}

void Wizard::cb_show_installed_apt_i(Fl_Round_Button*, void*) {
  show_installed(true);
}
void Wizard::cb_show_installed_apt(Fl_Round_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->user_data()))->cb_show_installed_apt_i(o,v);
}

void Wizard::cb_Advanced_i(Fl_Button*, void*) {
  advanced_cb();
}
void Wizard::cb_Advanced(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_Advanced_i(o,v);
}

void Wizard::cb_show_cmd_line_i(Fl_Check_Button*, void*) {
  show_cmd_line_cb();
}
void Wizard::cb_show_cmd_line(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_show_cmd_line_i(o,v);
}

void Wizard::cb_show_console_i(Fl_Check_Button*, void*) {
  show_console_cb();
}
void Wizard::cb_show_console(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_show_console_i(o,v);
}

void Wizard::cb_resolution_i(Fl_Choice*, void*) {
  resolution_cb();
}
void Wizard::cb_resolution(Fl_Choice* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_resolution_i(o,v);
}

unsigned char Wizard::menu_resolution_i18n_done = 0;
Fl_Menu_Item Wizard::menu_resolution[] = {
 {"800x600", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1024x768", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1280x1024", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1600x1200", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1280x800", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1680x1050", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1920x1200", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void Wizard::cb_game_mode_i(Fl_Check_Button*, void*) {
  game_mode_cb();
}
void Wizard::cb_game_mode(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_game_mode_i(o,v);
}

void Wizard::cb_horizon_effect_i(Fl_Check_Button*, void*) {
  horizon_effect_cb();
}
void Wizard::cb_horizon_effect(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_horizon_effect_i(o,v);
}

void Wizard::cb_enhanced_lighting_i(Fl_Check_Button*, void*) {
  enhanced_lighting_cb();
}
void Wizard::cb_enhanced_lighting(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_enhanced_lighting_i(o,v);
}

void Wizard::cb_specular_highlight_i(Fl_Check_Button*, void*) {
  specular_highlight_cb();
}
void Wizard::cb_specular_highlight(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_specular_highlight_i(o,v);
}

void Wizard::cb_frame_rate_limiter_i(Fl_Check_Button*, void*) {
  frame_rate_limiter_cb();
}
void Wizard::cb_frame_rate_limiter(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_frame_rate_limiter_i(o,v);
}

void Wizard::cb_frame_rate_limiter_value_i(Fl_Value_Input*, void*) {
  frame_rate_limiter_value_cb();
}
void Wizard::cb_frame_rate_limiter_value(Fl_Value_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_frame_rate_limiter_value_i(o,v);
}

void Wizard::cb_clouds_3d_i(Fl_Check_Button*, void*) {
  clouds_3d_cb();
}
void Wizard::cb_clouds_3d(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_clouds_3d_i(o,v);
}

void Wizard::cb_bpp_i(Fl_Choice*, void*) {
  bpp_cb();
}
void Wizard::cb_bpp(Fl_Choice* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->user_data()))->cb_bpp_i(o,v);
}

unsigned char Wizard::menu_bpp_i18n_done = 0;
Fl_Menu_Item Wizard::menu_bpp[] = {
 {"32", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"24", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"16", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void Wizard::cb_random_objects_i(Fl_Check_Button*, void*) {
  random_objects_cb();
}
void Wizard::cb_random_objects(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_random_objects_i(o,v);
}

void Wizard::cb_random_trees_i(Fl_Check_Button*, void*) {
  random_trees_cb();
}
void Wizard::cb_random_trees(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_random_trees_i(o,v);
}

void Wizard::cb_ai_models_i(Fl_Check_Button*, void*) {
  ai_models_cb();
}
void Wizard::cb_ai_models(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_ai_models_i(o,v);
}

void Wizard::cb_ai_traffic_i(Fl_Check_Button*, void*) {
  ai_traffic_cb();
}
void Wizard::cb_ai_traffic(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_ai_traffic_i(o,v);
}

void Wizard::cb_terrasync_i(Fl_Check_Button*, void*) {
  terrasync_cb();
}
void Wizard::cb_terrasync(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_terrasync_i(o,v);
}

void Wizard::cb_time_of_day_i(Fl_Check_Button*, void*) {
  time_of_day_cb();
}
void Wizard::cb_time_of_day(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_time_of_day_i(o,v);
}

void Wizard::cb_time_of_day_value_i(Fl_Choice*, void*) {
  time_of_day_value_cb();
}
void Wizard::cb_time_of_day_value(Fl_Choice* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_time_of_day_value_i(o,v);
}

void Wizard::cb_real_weather_fetch_i(Fl_Check_Button*, void*) {
  real_weather_fetch_cb();
}
void Wizard::cb_real_weather_fetch(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_real_weather_fetch_i(o,v);
}

void Wizard::cb_auto_coordination_i(Fl_Check_Button*, void*) {
  auto_coordination_cb();
}
void Wizard::cb_auto_coordination(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_auto_coordination_i(o,v);
}

void Wizard::cb_season_i(Fl_Choice*, void*) {
  season_cb();
}
void Wizard::cb_season(Fl_Choice* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_season_i(o,v);
}

void Wizard::cb_auto_visibility_i(Fl_Check_Button*, void*) {
  auto_visibility_cb();
}
void Wizard::cb_auto_visibility(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_auto_visibility_i(o,v);
}

void Wizard::cb_scenarii_i(Fl_Browser*, void*) {
  scenarii_cb();
}
void Wizard::cb_scenarii(Fl_Browser* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_scenarii_i(o,v);
}

void Wizard::cb_Deselect_i(Fl_Button*, void*) {
  deselect_all_scenarii_cb();
}
void Wizard::cb_Deselect(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_Deselect_i(o,v);
}

void Wizard::cb_atlas_i(Fl_Check_Button*, void*) {
  atlas_cb();
}
void Wizard::cb_atlas(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_atlas_i(o,v);
}

void Wizard::cb_atlas_host_i(Fl_Input*, void*) {
  atlas_host_cb();
}
void Wizard::cb_atlas_host(Fl_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_atlas_host_i(o,v);
}

void Wizard::cb_atlas_port_i(Fl_Value_Input*, void*) {
  atlas_port_cb();
}
void Wizard::cb_atlas_port(Fl_Value_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_atlas_port_i(o,v);
}

void Wizard::cb_multiplay_i(Fl_Check_Button*, void*) {
  multiplay_cb();
}
void Wizard::cb_multiplay(Fl_Check_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_multiplay_i(o,v);
}

void Wizard::cb_multiplay_callsign_i(Fl_Input*, void*) {
  multiplay_callsign_cb();
}
void Wizard::cb_multiplay_callsign(Fl_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_multiplay_callsign_i(o,v);
}

void Wizard::cb_multiplay_host_i(Fl_Input*, void*) {
  multiplay_field_cb();
}
void Wizard::cb_multiplay_host(Fl_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_multiplay_host_i(o,v);
}

void Wizard::cb_multiplay_in_i(Fl_Value_Input*, void*) {
  multiplay_field_cb();
}
void Wizard::cb_multiplay_in(Fl_Value_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_multiplay_in_i(o,v);
}

void Wizard::cb_multiplay_out_i(Fl_Value_Input*, void*) {
  multiplay_field_cb();
}
void Wizard::cb_multiplay_out(Fl_Value_Input* o, void* v) {
  ((Wizard*)(o->parent()->parent()->parent()->parent()->parent()->user_data()))->cb_multiplay_out_i(o,v);
}

void Wizard::cb_prev_i(Fl_Button*, void*) {
  prev_cb();
}
void Wizard::cb_prev(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->user_data()))->cb_prev_i(o,v);
}

void Wizard::cb_next_i(Fl_Button*, void*) {
  next_cb();
}
void Wizard::cb_next(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->user_data()))->cb_next_i(o,v);
}

void Wizard::cb_cancel_i(Fl_Button*, void*) {
  cancel_cb();
}
void Wizard::cb_cancel(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->user_data()))->cb_cancel_i(o,v);
}

void Wizard::cb_defaults_i(Fl_Button*, void*) {
  defaults_cb();
}
void Wizard::cb_defaults(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->user_data()))->cb_defaults_i(o,v);
}

void Wizard::cb_Save_i(Fl_Button*, void*) {
  save_preferences_cb();
}
void Wizard::cb_Save(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->user_data()))->cb_Save_i(o,v);
}

void Wizard::cb_Load_i(Fl_Button*, void*) {
  load_preferences_cb();
}
void Wizard::cb_Load(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->parent()->user_data()))->cb_Load_i(o,v);
}

void Wizard::cb_OK_i(Fl_Button*, void*) {
  crash_ok_cb();
}
void Wizard::cb_OK(Fl_Button* o, void* v) {
  ((Wizard*)(o->parent()->user_data()))->cb_OK_i(o,v);
}

Wizard::Wizard() : prefs( Fl_Preferences::USER, "flightgear.org", "fgrun" ), systemPrefs( Fl_Preferences::SYSTEM, "flightgear.org", "fgrun" ),logwin(0), folder_open_pixmap(folder_open_xpm), warning_pixmap(warning_xpm), question_pixmap(question_xpm), adv(0), fgThread(0), fgPid(0), tsPid(0), refreshAircraft(false) {
  { 
	  //=================================================
	char* pGB = "运行向导";
	char * pUTF8 = G2U(pGB);
	  
    win = new Fl_Double_Window(800, 600, pUTF8);
    win->user_data((void*)(this));
    { wiz = new Fl_Wizard(0, 0, 800, 560);
      { pGB = "选择路径";
		pUTF8 = G2U(pGB);
		page[0] = new Fl_Group(0, 0, 800, 560,pUTF8);
        page[0]->labelfont(1);
        page[0]->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
        page[0]->hide();
        { about_ = new Fl_Help_View(5, 25, 790, 130);
          about_->labeltype(FL_NO_LABEL);
        } // Fl_Help_View* about_
        { pGB = "可执行";
		  pUTF8 = G2U(pGB);
		  fg_exe_ = new Fl_Input(130, 175, 495, 25, pUTF8);
          fg_exe_->tooltip(_("Full pathname to FlightGear executable"));
          fg_exe_->labelsize(12);
          fg_exe_->textsize(12);
          fg_exe_->callback((Fl_Callback*)cb_fg_exe_);
          fg_exe_->when(FL_WHEN_CHANGED);
        } // Fl_Input* fg_exe_
        { Fl_Button* o = new Fl_Button(630, 175, 25, 25);
          o->tooltip(_("Full pathname to FlightGear executable"));
          o->labelsize(12);
          o->callback((Fl_Callback*)cb_);
          o->image(folder_open_pixmap);
        } // Fl_Button* o
        { Fl_Box* o = fg_exe_invalid = new Fl_Box(660, 175, 25, 25);
          fg_exe_invalid->tooltip(_("Executable path not set or invalid"));
          fg_exe_invalid->hide();
          o->image(warning_pixmap);
        } // Fl_Box* fg_exe_invalid
        { pGB = "根目录";
		  pUTF8 = G2U(pGB);
		  fg_root_ = new Fl_Input(130, 205, 495, 25, pUTF8);
          fg_root_->tooltip(_("root data path"));
          fg_root_->labelsize(12);
          fg_root_->textsize(12);
          fg_root_->callback((Fl_Callback*)cb_fg_root_);
          fg_root_->when(FL_WHEN_CHANGED);
        } // Fl_Input* fg_root_
        { Fl_Button* o = new Fl_Button(630, 205, 25, 25);
          o->tooltip(_("root data path"));
          o->labelsize(12);
          o->callback((Fl_Callback*)cb_1);
          o->image(folder_open_pixmap);
        } // Fl_Button* o
        { Fl_Box* o = fg_root_invalid = new Fl_Box(660, 205, 25, 25);
          fg_root_invalid->tooltip(_("FG_ROOT path invalid or not set"));
          fg_root_invalid->hide();
          o->image(warning_pixmap);
        } // Fl_Box* fg_root_invalid
        { Fl_Group* o = new Fl_Group(130, 235, 495, 225);
          { Fl_Group* o = new Fl_Group(130, 235, 495, 115);
            { pGB = "飞机";
			  pUTF8 = G2U(pGB);
			  aircraft_dir_list_ = new Fl_Browser(130, 235, 495, 80, pUTF8);
              aircraft_dir_list_->tooltip(_("Aircraft directories"));
              aircraft_dir_list_->type(2);
              aircraft_dir_list_->labelsize(12);
              aircraft_dir_list_->textsize(12);
              aircraft_dir_list_->callback((Fl_Callback*)cb_aircraft_dir_list_);
              aircraft_dir_list_->align(Fl_Align(FL_ALIGN_LEFT));
              Fl_Group::current()->resizable(aircraft_dir_list_);
            } // Fl_Browser* aircraft_dir_list_
            { Fl_Group* o = new Fl_Group(130, 320, 495, 25);
              { pGB = "添加";
			    pUTF8 = G2U(pGB);
				Fl_Button* o = new Fl_Button(130, 320, 100, 25,pUTF8);
                o->tooltip(_("Add an aircraft directory"));
                o->labelsize(12);
                o->callback((Fl_Callback*)cb_Add);
              } // Fl_Button* o
              { pGB = "删除";
			    pUTF8 = G2U(pGB);
				aircraft_dir_delete_ = new Fl_Button(235, 320, 100, 25,pUTF8);
                aircraft_dir_delete_->tooltip(_("Delete an aircraft directory"));
                aircraft_dir_delete_->labelsize(12);
                aircraft_dir_delete_->callback((Fl_Callback*)cb_aircraft_dir_delete_);
                aircraft_dir_delete_->deactivate();
              } // Fl_Button* aircraft_dir_delete_
              { Fl_Box* o = new Fl_Box(340, 320, 285, 25);
                Fl_Group::current()->resizable(o);
              } // Fl_Box* o
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          { Fl_Group* o = new Fl_Group(130, 350, 495, 115);
            {  pGB = "环境";
			   pUTF8 = G2U(pGB);
			  scenery_dir_list_ = new Fl_Browser(130, 350, 495, 80, pUTF8);
              scenery_dir_list_->tooltip(_("Scenery directories"));
              scenery_dir_list_->type(2);
              scenery_dir_list_->labelsize(12);
              scenery_dir_list_->textsize(12);
              scenery_dir_list_->callback((Fl_Callback*)cb_scenery_dir_list_);
              scenery_dir_list_->align(Fl_Align(FL_ALIGN_LEFT));
              Fl_Group::current()->resizable(scenery_dir_list_);
            } // Fl_Browser* scenery_dir_list_
            { Fl_Group* o = new Fl_Group(130, 435, 495, 25);
              { pGB = "添加";
			    pUTF8 = G2U(pGB);
				Fl_Button* o = new Fl_Button(130, 435, 100, 25,pUTF8);
                o->tooltip(_("Add a scenery directory"));
                o->labelsize(12);
                o->callback((Fl_Callback*)cb_Add1);
              } // Fl_Button* o
              { pGB = "删除";
			    pUTF8 = G2U(pGB);
				scenery_dir_delete_ = new Fl_Button(235, 435, 100, 25,pUTF8);
                scenery_dir_delete_->tooltip(_("Delete a scenery directory"));
                scenery_dir_delete_->labelsize(12);
                scenery_dir_delete_->callback((Fl_Callback*)cb_scenery_dir_delete_);
                scenery_dir_delete_->deactivate();
              } // Fl_Button* scenery_dir_delete_
              { Fl_Box* o = new Fl_Box(355, 435, 50, 25);
                Fl_Group::current()->resizable(o);
              } // Fl_Box* o
              o->end();
            } // Fl_Group* o
            o->end();
          } // Fl_Group* o
          o->end();
          Fl_Group::current()->resizable(o);
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(630, 350, 25, 40);
          { scenery_dir_up_ = new Fl_Button(630, 365, 25, 25, _("@8>"));
            scenery_dir_up_->tooltip(_("Move scenery directory up"));
            scenery_dir_up_->callback((Fl_Callback*)cb_scenery_dir_up_);
            scenery_dir_up_->deactivate();
          } // Fl_Button* scenery_dir_up_
          { Fl_Box* o = new Fl_Box(630, 350, 25, 15);
            Fl_Group::current()->resizable(o);
          } // Fl_Box* o
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(630, 390, 25, 40);
          { scenery_dir_down_ = new Fl_Button(630, 395, 25, 25, _("@2>"));
            scenery_dir_down_->tooltip(_("Move scenery directory down"));
            scenery_dir_down_->callback((Fl_Callback*)cb_scenery_dir_down_);
            scenery_dir_down_->deactivate();
          } // Fl_Button* scenery_dir_down_
          { Fl_Box* o = new Fl_Box(630, 420, 25, 10);
            Fl_Group::current()->resizable(o);
          } // Fl_Box* o
          o->end();
        } // Fl_Group* o
        { Fl_Box* o = fg_scenery_invalid = new Fl_Box(660, 350, 25, 25);
          fg_scenery_invalid->tooltip(_("FG_SCENERY empty"));
          fg_scenery_invalid->hide();
          o->image(warning_pixmap);
        } // Fl_Box* fg_scenery_invalid
        { pGB = "删除";
		  pUTF8 = G2U(pGB);
		  cache_delete_ = new Fl_Button(630, 505, 60, 25,pUTF8);
          cache_delete_->tooltip(_("Clear the content of the airport cache"));
          cache_delete_->labelsize(12);
          cache_delete_->callback((Fl_Callback*)cb_cache_delete_);
          cache_delete_->deactivate();
        } // Fl_Button* cache_delete_
        { pGB = "机场高速缓存";
		  pUTF8 = G2U(pGB);
		  cache_file_ = new Fl_Output(130, 505, 495, 25,pUTF8);
          cache_file_->tooltip(_("Full path to the airport cache"));
          cache_file_->labelsize(12);
          cache_file_->textsize(12);
        } // Fl_Output* cache_file_
        page[0]->end();
      } // Fl_Group* page[0]
      { pGB = "选择一个飞机";
		pUTF8 = G2U(pGB);
		page[1] = new Fl_Group(0, 0, 800, 560,pUTF8);
        page[1]->labelfont(1);
        page[1]->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
        { pGB = "3D 预览";
		  pUTF8 = G2U(pGB);
		  show_3d_preview = new Fl_Check_Button(780, 0, 17, 25,pUTF8);
          show_3d_preview->down_box(FL_DOWN_BOX);
          show_3d_preview->labelsize(12);
          show_3d_preview->callback((Fl_Callback*)cb_show_3d_preview);
          show_3d_preview->align(Fl_Align(FL_ALIGN_LEFT));
        } // Fl_Check_Button* show_3d_preview
        { Fl_Tile* o = new Fl_Tile(0, 25, 795, 465);
          { Fl_Group* o = new Fl_Group(5, 25, 200, 465);
            { pGB = "最近使用的飞机";
		      pUTF8 = G2U(pGB);
			  aircraft_mru = new Fl_Browser(5, 35, 200, 105,pUTF8);
              aircraft_mru->type(2);
              aircraft_mru->labelfont(1);
              aircraft_mru->labelsize(12);
              aircraft_mru->textsize(12);
              aircraft_mru->callback((Fl_Callback*)cb_aircraft_mru);
              aircraft_mru->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            } // Fl_Browser* aircraft_mru
            { pGB = "可用的飞机";
		      pUTF8 = G2U(pGB);
			  aircraft = new Fl_Browser(5, 160, 200, 330,pUTF8 );
              aircraft->type(2);
              aircraft->labelfont(1);
              aircraft->labelsize(12);
              aircraft->textsize(12);
              aircraft->callback((Fl_Callback*)cb_aircraft);
              aircraft->align(Fl_Align(FL_ALIGN_TOP_LEFT));
              Fl_Group::current()->resizable(aircraft);
            } // Fl_Browser* aircraft
            o->end();
          } // Fl_Group* o
          { pGB = "预览";
			pUTF8 = G2U(pGB);
			preview = new Fl_OSG(205, 25, 590, 465,	pUTF8);
            preview->box(FL_THIN_DOWN_BOX);
            preview->color(FL_BACKGROUND_COLOR);
            preview->selection_color(FL_BACKGROUND_COLOR);
            preview->labeltype(FL_NORMAL_LABEL);
            preview->labelfont(0);
            preview->labelsize(12);
            preview->labelcolor(FL_FOREGROUND_COLOR);
            preview->align(Fl_Align(FL_ALIGN_CENTER));
            preview->when(FL_WHEN_RELEASE);
          } // Fl_OSG* preview
          { Fl_Box* o = new Fl_Box(80, 190, 265, 65);
            o->hide();
            Fl_Group::current()->resizable(o);
          } // Fl_Box* o
          o->end();
          Fl_Group::current()->resizable(o);
        } // Fl_Tile* o
        { Fl_Group* o = new Fl_Group(5, 490, 790, 65);
          o->box(FL_DOWN_BOX);
          { pGB = "状态:";
			pUTF8 = G2U(pGB);
			aircraft_status = new Fl_Output(115, 495, 135, 25,pUTF8);
          } // Fl_Output* aircraft_status
          { pGB = "作者(年代):";
			pUTF8 = G2U(pGB);
			aircraft_author = new Fl_Output(385, 495, 305, 25,pUTF8);
            Fl_Group::current()->resizable(aircraft_author);
          } // Fl_Output* aircraft_author
          { pGB = "查看器";
			pUTF8 = G2U(pGB);
			start_viewer = new Fl_Button(695, 495, 95, 25,pUTF8);
            start_viewer->callback((Fl_Callback*)cb_start_viewer);
          } // Fl_Button* start_viewer
          { pGB = "地点:";
			pUTF8 = G2U(pGB);
			aircraft_location = new Fl_Output(115, 525, 575, 25,pUTF8);
          } // Fl_Output* aircraft_location
          o->end();
        } // Fl_Group* o
        page[1]->end();
      } // Fl_Group* page[1]
      { pGB = "选择一个位置";
		pUTF8 = G2U(pGB);
		page[2] = new Fl_Group(0, 0, 800, 560, pUTF8);
        page[2]->labelfont(1);
        page[2]->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
        page[2]->hide();
        { pGB = "所有的机场";
		  pUTF8 = G2U(pGB);
		  show_all_apt = new Fl_Round_Button(5, 20, 100, 15, pUTF8);
          show_all_apt->tooltip(_("Display all airports"));
          show_all_apt->type(102);
          show_all_apt->down_box(FL_ROUND_DOWN_BOX);
          show_all_apt->callback((Fl_Callback*)cb_show_all_apt);
        } // Fl_Round_Button* show_all_apt
        { pGB = "安装了机场";
		  pUTF8 = G2U(pGB);
		  show_installed_apt = new Fl_Round_Button(5, 40, 100, 15,pUTF8);
          show_installed_apt->tooltip(_("Display only installed airports"));
          show_installed_apt->type(102);
          show_installed_apt->down_box(FL_ROUND_DOWN_BOX);
          show_installed_apt->value(1);
          show_installed_apt->callback((Fl_Callback*)cb_show_installed_apt);
        } // Fl_Round_Button* show_installed_apt
        { airports_ = new AirportBrowser(5, 55, 790, 415);
          airports_->box(FL_NO_BOX);
          airports_->color(FL_BACKGROUND_COLOR);
          airports_->selection_color(FL_BACKGROUND_COLOR);
          airports_->labeltype(FL_NORMAL_LABEL);
          airports_->labelfont(0);
          airports_->labelsize(14);
          airports_->labelcolor(FL_FOREGROUND_COLOR);
          airports_->align(Fl_Align(FL_ALIGN_CENTER));
          airports_->when(FL_WHEN_RELEASE);
          Fl_Group::current()->resizable(airports_);
        } // AirportBrowser* airports_
        { Fl_Group* o = new Fl_Group(5, 505, 790, 50);
          { pGB = "运营商运维";
		    pUTF8 = G2U(pGB);
			carrier_group = new Fl_Group(5, 505, 635, 50, pUTF8);
			//carrier_group = new Fl_Group(5, 505, 635, 50, _("Carrier Ops"));  //翻译不太正确
            carrier_group->box(FL_ENGRAVED_FRAME);
            carrier_group->labelfont(1);
            carrier_group->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
            { pGB = "航空公司:";
		      pUTF8 = G2U(pGB);
			  carrier_ = new Fl_Input(145, 520, 175, 25, pUTF8);
            } // Fl_Input* carrier_
            { pGB = "公园pos:";
		      pUTF8 = G2U(pGB);
			  parkpos_ = new Fl_Input(460, 520, 175, 25,pUTF8);
			 // parkpos_ = new Fl_Input(460, 520, 175, 25, _("Park pos :"));
              parkpos_->tooltip(_("Only valid if carrier is set. For airport parking, use the list above."));
            } // Fl_Input* parkpos_
            { Fl_Box* o = new Fl_Box(640, 505, 0, 5);
              Fl_Group::current()->resizable(o);
            } // Fl_Box* o
            carrier_group->end();
            Fl_Group::current()->resizable(carrier_group);
          } // Fl_Group* carrier_group
          o->end();
        } // Fl_Group* o
        page[2]->end();
      } // Fl_Group* page[2]
      { page[3] = new Fl_Group(0, 0, 800, 560);
        page[3]->hide();
        { Fl_Group* o = new Fl_Group(0, 525, 800, 25);
          { pGB = "先进的";
		    pUTF8 = G2U(pGB);
			Fl_Button* o = new Fl_Button(685, 525, 110, 25,pUTF8);
			//Fl_Button* o = new Fl_Button(685, 525, 110, 25, _("Advanced..."));
            o->callback((Fl_Callback*)cb_Advanced);
          } // Fl_Button* o
          { Fl_Box* o = new Fl_Box(250, 525, 435, 25);
            Fl_Group::current()->resizable(o);
          } // Fl_Box* o
          { pGB = "显示命令行";
		    pUTF8 = G2U(pGB);
			show_cmd_line = new Fl_Check_Button(10, 525, 240, 25, pUTF8);
            show_cmd_line->down_box(FL_DOWN_BOX);
            show_cmd_line->callback((Fl_Callback*)cb_show_cmd_line);
          } // Fl_Check_Button* show_cmd_line
          { pGB = "显示控制台";
		    pUTF8 = G2U(pGB);
			show_console = new Fl_Check_Button(280, 525, 240, 25, pUTF8);
            show_console->down_box(FL_DOWN_BOX);
            show_console->callback((Fl_Callback*)cb_show_console);
          } // Fl_Check_Button* show_console
          o->end();
        } // Fl_Group* o
        { text = new Fl_Text_Display(5, 370, 790, 145);
          text->box(FL_THIN_DOWN_BOX);
          text->align(Fl_Align(FL_ALIGN_LEFT));
          text->hide();
        } // Fl_Text_Display* text
        { pGB = "显示";
		  pUTF8 = G2U(pGB);
		  Fl_Group* o = new Fl_Group(5, 5, 790, 110, pUTF8);
          o->box(FL_ENGRAVED_FRAME);
          o->labelfont(1);
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
          { pGB = "解决方法:";
		    pUTF8 = G2U(pGB);
			resolution = new Fl_Choice(100, 30, 125, 25, pUTF8);
            resolution->tooltip(_("Window geometry, WxH"));
            resolution->down_box(FL_BORDER_BOX);
            resolution->callback((Fl_Callback*)cb_resolution);
            if (!menu_resolution_i18n_done) {
              int i=0;
              for ( ; i<7; i++)
                if (menu_resolution[i].label())
                  menu_resolution[i].label(_(menu_resolution[i].label()));
              menu_resolution_i18n_done = 1;
            }
            resolution->menu(menu_resolution);
          } // Fl_Choice* resolution
          { game_mode = new Fl_Check_Button(25, 85, 210, 25, _("Full Screen"));
            game_mode->down_box(FL_DOWN_BOX);
            game_mode->callback((Fl_Callback*)cb_game_mode);
          } // Fl_Check_Button* game_mode
          { pGB = "地平线效应";
		    pUTF8 = G2U(pGB);
			horizon_effect = new Fl_Check_Button(250, 10, 205, 25, pUTF8);
            horizon_effect->down_box(FL_DOWN_BOX);
            horizon_effect->callback((Fl_Callback*)cb_horizon_effect);
          } // Fl_Check_Button* horizon_effect
          { pGB = "增强跑道照明";
		    pUTF8 = G2U(pGB);
			enhanced_lighting = new Fl_Check_Button(250, 35, 205, 25,pUTF8);
            enhanced_lighting->tooltip(_("Use with caution. It may drop your framerate dramatically"));
            enhanced_lighting->down_box(FL_DOWN_BOX);
            enhanced_lighting->callback((Fl_Callback*)cb_enhanced_lighting);
          } // Fl_Check_Button* enhanced_lighting
          { pGB = "反射高光";
		    pUTF8 = G2U(pGB);
			specular_highlight = new Fl_Check_Button(250, 60, 205, 25, pUTF8);
			//specular_highlight = new Fl_Check_Button(250, 60, 205, 25, _("Specular highlight"));
            specular_highlight->down_box(FL_DOWN_BOX);
            specular_highlight->callback((Fl_Callback*)cb_specular_highlight);
          } // Fl_Check_Button* specular_highlight
          { pGB = "帧速率限制器:";
		    pUTF8 = G2U(pGB);
			frame_rate_limiter = new Fl_Check_Button(250, 85, 205, 25, pUTF8);
            frame_rate_limiter->tooltip(_("Too much framerate hurts the smoothness of the simulation"));
            frame_rate_limiter->down_box(FL_DOWN_BOX);
            frame_rate_limiter->callback((Fl_Callback*)cb_frame_rate_limiter);
          } // Fl_Check_Button* frame_rate_limiter
          { frame_rate_limiter_value = new Fl_Value_Input(455, 85, 55, 25);
            frame_rate_limiter_value->minimum(30);
            frame_rate_limiter_value->maximum(100);
            frame_rate_limiter_value->step(1);
            frame_rate_limiter_value->callback((Fl_Callback*)cb_frame_rate_limiter_value);
          } // Fl_Value_Input* frame_rate_limiter_value
          { Fl_Box* o = new Fl_Box(610, 80, 25, 10);
            Fl_Group::current()->resizable(o);
          } // Fl_Box* o
          { pGB = "三维云";
		    pUTF8 = G2U(pGB);
			clouds_3d = new Fl_Check_Button(470, 10, 205, 25,  pUTF8);
			//clouds_3d = new Fl_Check_Button(470, 10, 205, 25, _("3D Clouds"));
            clouds_3d->down_box(FL_DOWN_BOX);
            clouds_3d->callback((Fl_Callback*)cb_clouds_3d);
          } // Fl_Check_Button* clouds_3d
          { pGB = "bpp :";
		    pUTF8 = G2U(pGB);
			bpp = new Fl_Choice(100, 55, 125, 25,pUTF8);
			//bpp = new Fl_Choice(100, 55, 125, 25, _("bpp :"));  不知道怎么翻译
            bpp->tooltip(_("Color depth (bits per pixel)"));
            bpp->down_box(FL_BORDER_BOX);
            bpp->callback((Fl_Callback*)cb_bpp);
            if (!menu_bpp_i18n_done) {
              int i=0;
              for ( ; i<3; i++)
                if (menu_bpp[i].label())
                  menu_bpp[i].label(_(menu_bpp[i].label()));
              menu_bpp_i18n_done = 1;
            }
            bpp->menu(menu_bpp);
          } // Fl_Choice* bpp
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(5, 120, 790, 180);
          { pGB = "特性";
		    pUTF8 = G2U(pGB);
			Fl_Group* o = new Fl_Group(5, 120, 480, 180,pUTF8);
            o->box(FL_ENGRAVED_FRAME);
            o->labelfont(1);
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
            { pGB = "随机的对象";
		      pUTF8 = G2U(pGB);
			  random_objects = new Fl_Check_Button(25, 135, 150, 25,pUTF8);
              random_objects->down_box(FL_DOWN_BOX);
              random_objects->callback((Fl_Callback*)cb_random_objects);
            } // Fl_Check_Button* random_objects
            { pGB = "随机森林";
		      pUTF8 = G2U(pGB);
			  random_trees = new Fl_Check_Button(25, 160, 150, 25,pUTF8);
			  //random_trees = new Fl_Check_Button(25, 160, 150, 25, _("Random trees"));
              random_trees->down_box(FL_DOWN_BOX);
              random_trees->callback((Fl_Callback*)cb_random_trees);
            } // Fl_Check_Button* random_trees
            { pGB = "人工智能模型";
		      pUTF8 = G2U(pGB);
			  ai_models = new Fl_Check_Button(25, 185, 150, 25,pUTF8);
              ai_models->down_box(FL_DOWN_BOX);
              ai_models->callback((Fl_Callback*)cb_ai_models);
            } // Fl_Check_Button* ai_models
            { pGB = "人工智能交通";
		      pUTF8 = G2U(pGB);
			  ai_traffic = new Fl_Check_Button(35, 210, 140, 25,pUTF8);
              ai_traffic->down_box(FL_DOWN_BOX);
              ai_traffic->callback((Fl_Callback*)cb_ai_traffic);
            } // Fl_Check_Button* ai_traffic
            { terrasync = new Fl_Check_Button(25, 235, 150, 25, _("TerraSync")); 
              terrasync->down_box(FL_DOWN_BOX);
              terrasync->callback((Fl_Callback*)cb_terrasync);
            } // Fl_Check_Button* terrasync
            { pGB = "每天的时间:";
		      pUTF8 = G2U(pGB);
			  time_of_day = new Fl_Check_Button(180, 135, 160, 25, pUTF8);//_("Time of day :")
              time_of_day->down_box(FL_DOWN_BOX);
              time_of_day->callback((Fl_Callback*)cb_time_of_day);
            } // Fl_Check_Button* time_of_day
            { time_of_day_value = new Fl_Choice(345, 135, 120, 25);
              time_of_day_value->down_box(FL_BORDER_BOX);
              time_of_day_value->callback((Fl_Callback*)cb_time_of_day_value);
            } // Fl_Choice* time_of_day_value
            { pGB = "实际天气取回";
		      pUTF8 = G2U(pGB);
			  real_weather_fetch = new Fl_Check_Button(180, 185, 160, 25,pUTF8);//_("Real weather fetch")
              real_weather_fetch->down_box(FL_DOWN_BOX);
              real_weather_fetch->callback((Fl_Callback*)cb_real_weather_fetch);
            } // Fl_Check_Button* real_weather_fetch
            { pGB = "自动协调";
		      pUTF8 = G2U(pGB);
			  auto_coordination = new Fl_Check_Button(180, 210, 170, 25,pUTF8);//_("Auto-coordination")
              auto_coordination->down_box(FL_DOWN_BOX);
              auto_coordination->callback((Fl_Callback*)cb_auto_coordination);
            } // Fl_Check_Button* auto_coordination
            { pGB = "季节:";
		      pUTF8 = G2U(pGB);
			  season = new Fl_Choice(345, 160, 120, 25, pUTF8);//_("Season :")
              season->down_box(FL_BORDER_BOX);
              season->callback((Fl_Callback*)cb_season);
            } // Fl_Choice* season
            { Fl_Box* o = new Fl_Box(445, 205, 20, 10);
              Fl_Group::current()->resizable(o);
            } // Fl_Box* o
            { pGB = "菜单-自动可见";
		      pUTF8 = G2U(pGB);
			  auto_visibility = new Fl_Check_Button(180, 235, 170, 25, pUTF8);//_("Menu auto-visibility")
              auto_visibility->down_box(FL_DOWN_BOX);
              auto_visibility->callback((Fl_Callback*)cb_auto_visibility);
            } // Fl_Check_Button* auto_visibility
            o->end();
          } // Fl_Group* o
          { pGB = "场景";
		    pUTF8 = G2U(pGB);
			Fl_Group* o = new Fl_Group(490, 120, 305, 174,pUTF8);//_("Scenarios")
            o->box(FL_ENGRAVED_FRAME);
            o->labelfont(1);
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
            { scenarii = new Fl_Browser(495, 136, 295, 123);
              scenarii->tooltip(_("Ctrl-click to select or deselect a single item"));
              scenarii->type(3);
              scenarii->callback((Fl_Callback*)cb_scenarii);
              scenarii->align(Fl_Align(FL_ALIGN_TOP_LEFT));
              Fl_Group::current()->resizable(scenarii);
            } // Fl_Browser* scenarii
            { Fl_Group* o = new Fl_Group(495, 265, 295, 25);
              {  pGB = "取消全选";
		         pUTF8 = G2U(pGB);
				 Fl_Button* o = new Fl_Button(495, 265, 265, 25, pUTF8);//_("Deselect all")
                o->tooltip(_("Ctrl-click to deselect a single item"));
                o->callback((Fl_Callback*)cb_Deselect);
                Fl_Group::current()->resizable(o);
              } // Fl_Button* o
              { Fl_Box* o = scenarii_help = new Fl_Box(765, 265, 25, 25);
                o->image(question_pixmap);
              } // Fl_Box* scenarii_help
              o->end();
            } // Fl_Group* o
            o->end();
            Fl_Group::current()->resizable(o);
          } // Fl_Group* o
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(5, 305, 790, 60);
          { atlas_group = new Fl_Group(5, 305, 245, 60);
            atlas_group->box(FL_ENGRAVED_FRAME);
            atlas_group->labeltype(FL_SHADOW_LABEL);
            atlas_group->labelfont(1);
            atlas_group->align(Fl_Align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE));
            { pGB = "地图";
		      pUTF8 = G2U(pGB);
			  atlas = new Fl_Check_Button(10, 310, 70, 25, pUTF8);//_("Atlas")
              atlas->down_box(FL_DOWN_BOX);
              atlas->labelfont(1);
              atlas->callback((Fl_Callback*)cb_atlas);
            } // Fl_Check_Button* atlas
            { pGB = "主机名:";
		      pUTF8 = G2U(pGB);
			  atlas_host = new Fl_Input(95, 335, 85, 25, pUTF8);//_("Hostname :")
              atlas_host->tooltip(_("Hostname"));
              atlas_host->callback((Fl_Callback*)cb_atlas_host);
              atlas_host->when(FL_WHEN_CHANGED);
              Fl_Group::current()->resizable(atlas_host);
            } // Fl_Input* atlas_host
            { atlas_port = new Fl_Value_Input(190, 335, 50, 25, _(":"));
              atlas_port->callback((Fl_Callback*)cb_atlas_port);
            } // Fl_Value_Input* atlas_port
            atlas_group->end();
          } // Fl_Group* atlas_group
          { multiplay_group = new Fl_Group(255, 305, 540, 60);
            multiplay_group->box(FL_ENGRAVED_FRAME);
            { pGB = "多玩家";
		      pUTF8 = G2U(pGB);
			  multiplay = new Fl_Check_Button(260, 310, 130, 25, pUTF8);//_("Multiplayer")
              multiplay->down_box(FL_DOWN_BOX);
              multiplay->labelfont(1);
              multiplay->callback((Fl_Callback*)cb_multiplay);
            } // Fl_Check_Button* multiplay
            { pGB = "呼号:";
		      pUTF8 = G2U(pGB);
			  multiplay_callsign = new Fl_Input(545, 310, 170, 25, pUTF8);//_("Callsign :")
              multiplay_callsign->callback((Fl_Callback*)cb_multiplay_callsign);
              multiplay_callsign->when(FL_WHEN_CHANGED);
            } // Fl_Input* multiplay_callsign
            { pGB = "主机名:";
		      pUTF8 = G2U(pGB);
			  multiplay_host = new Fl_Input(355, 335, 120, 25, pUTF8);//_("Hostname :")
              multiplay_host->tooltip(_("Peer hostname"));
              multiplay_host->callback((Fl_Callback*)cb_multiplay_host);
              multiplay_host->when(FL_WHEN_CHANGED);
              Fl_Group::current()->resizable(multiplay_host);
            } // Fl_Input* multiplay_host
            { multiplay_in = new Fl_Value_Input(545, 335, 50, 25, _("in :"));
              multiplay_in->tooltip(_("Input port number"));
              multiplay_in->callback((Fl_Callback*)cb_multiplay_in);
            } // Fl_Value_Input* multiplay_in
            { multiplay_out = new Fl_Value_Input(665, 335, 50, 25, _("out :"));
              multiplay_out->tooltip(_("Output port number"));
              multiplay_out->callback((Fl_Callback*)cb_multiplay_out);
            } // Fl_Value_Input* multiplay_out
            multiplay_group->end();
            Fl_Group::current()->resizable(multiplay_group);
          } // Fl_Group* multiplay_group
          o->end();
        } // Fl_Group* o
        { Fl_Box* o = new Fl_Box(245, 370, 280, 145);
          Fl_Group::current()->resizable(o);
        } // Fl_Box* o
        page[3]->end();
      } // Fl_Group* page[3]
      { page[4] = new Fl_Group(0, 0, 800, 560);
        page[4]->hide();
        page[4]->deactivate();
        page[4]->end();
      } // Fl_Group* page[4]
      win->resizable( wiz );
      wiz->end();
    } // Fl_Wizard* wiz
    { Fl_Group* o = new Fl_Group(0, 570, 800, 25);
      { pGB = "上一页";
		pUTF8 = G2U(pGB);
		prev = new Fl_Button(575, 570, 70, 25, pUTF8);//_("Prev")
        prev->labelsize(12);
        prev->callback((Fl_Callback*)cb_prev);
      } // Fl_Button* prev
      { pGB = "下一页";
		pUTF8 = G2U(pGB);
		next = new Fl_Button(650, 570, 70, 25, pUTF8);//_("Next")
        next->labelsize(12);
        next->callback((Fl_Callback*)cb_next);
      } // Fl_Button* next
      { pGB = "退出";
		pUTF8 = G2U(pGB);
		cancel = new Fl_Button(725, 570, 70, 25, pUTF8);//_("Quit")
        cancel->labelsize(12);
        cancel->callback((Fl_Callback*)cb_cancel);
      } // Fl_Button* cancel
      { Fl_Box* o = new Fl_Box(380, 570, 195, 25);
        Fl_Group::current()->resizable(o);
      } // Fl_Box* o
      { pGB = "恢复默认设置";
		pUTF8 = G2U(pGB);
		defaults = new Fl_Button(5, 570, 165, 25,pUTF8);//_("Restore default settings")
        defaults->tooltip(_("Clear all selected options and return to the install situation. Useful if FGF\
S don\'t start anymore."));
        defaults->labelsize(12);
        defaults->callback((Fl_Callback*)cb_defaults);
      } // Fl_Button* defaults
      { pGB = "另存为";
		pUTF8 = G2U(pGB);
		Fl_Button* o = new Fl_Button(300, 570, 120, 25, pUTF8);//_("Save As...")
        o->tooltip(_("Save current configuration to a file"));
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Save);
      } // Fl_Button* o
      { pGB = "负载";
		pUTF8 = G2U(pGB);
		Fl_Button* o = new Fl_Button(175, 570, 120, 25, pUTF8);//_("Load")
        o->tooltip(_("Load a previously saved configuration"));
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Load);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    win->end();
  } // Fl_Double_Window* win
}

Fl_Double_Window* Wizard::make_launch_window() {
  { char* pGB = "飞机启动...";
	char* PUTF8 = G2U(pGB);
	launch_window = new Fl_Double_Window(455, 155, PUTF8);//_("FlightGear running...")
    launch_window->user_data((void*)(this));
    { Fl_Group* o = new Fl_Group(15, 25, 425, 120);
      { pGB = "飞机已经启动";
	    PUTF8 = G2U(pGB);
		Fl_Box* o = new Fl_Box(15, 25, 425, 25, PUTF8);//_("FlightGear has been started")
        o->labelfont(1);
        o->labelsize(18);
        o->align(Fl_Align(FL_ALIGN_WRAP));
      } // Fl_Box* o
      { pGB = "请稍等";
	    PUTF8 = G2U(pGB);
		Fl_Box* o = new Fl_Box(15, 50, 425, 25,PUTF8);//_("Please wait...")
        o->labelfont(1);
      } // Fl_Box* o
      { pGB = "改变飞机、退出FlightGear和回到这个发射器";
	    PUTF8 = G2U(pGB);
		Fl_Box* o = new Fl_Box(95, 90, 265, 50, PUTF8);//_("To change aircraft, exit FlightGear and return to this launcher")
        o->labelfont(1);
        o->align(Fl_Align(FL_ALIGN_WRAP));
      } // Fl_Box* o
      o->end();
    } // Fl_Group* o
    launch_window->end();
  } // Fl_Double_Window* launch_window
  return launch_window;
}

Fl_Double_Window* Wizard::make_crash_window() {
  { char* pGB = "飞机坠毁";
	char* PUTF8 = G2U(pGB);
	crash_window = new Fl_Double_Window(455, 240,PUTF8);//_("Flightgear crashed...")
    crash_window->user_data((void*)(this));
    { pGB = "Flightgear遇到了一个意想不到的失败";
	  PUTF8 = G2U(pGB);
	  Fl_Box* o = new Fl_Box(5, 15, 445, 25,PUTF8);//_("Flightgear encountered an unexpected failure")
      o->labelfont(1);
      o->labelsize(18);
    } // Fl_Box* o
    { pGB = "对给您带来的不便我们很抱歉";
	  PUTF8 = G2U(pGB);
	  Fl_Box* o = new Fl_Box(5, 40, 445, 25,PUTF8);// _("We are sorry for this inconvenience.")
      o->labelfont(1);
    } // Fl_Box* o
    { file_box = new Fl_Box(5, 90, 445, 55);
      file_box->align(Fl_Align(132|FL_ALIGN_INSIDE));
    } // Fl_Box* file_box
    { Fl_Button* o = new Fl_Button(350, 205, 100, 30, _("OK"));
      o->labelsize(12);
      o->callback((Fl_Callback*)cb_OK);
    } // Fl_Button* o
    { pGB = "在下面的文件中生成一个错误报告:";
	  PUTF8 = G2U(pGB);
	  Fl_Box* o = new Fl_Box(5, 65, 445, 25,PUTF8);//_("An error report has been generated in the file below :")
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    { pGB = "请将这个错误报告Flightgear开发团队";
	  PUTF8 = G2U(pGB);
	  Fl_Box* o = new Fl_Box(5, 145, 445, 50, PUTF8);//_("Please send this error report to the Flightgear development team")
      o->labelsize(12);
      o->align(Fl_Align(133|FL_ALIGN_INSIDE));
    } // Fl_Box* o
    crash_window->end();
  } // Fl_Double_Window* crash_window
  return crash_window;
}
